version: '3'
services:
  app:
    build: ./docker/app
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/home/docker/app
